include("$(PORT_DIR)/boards/manifest.py")
#freeze("modules")
include("$(MPY_DIR)/extmod/upyscripts_eliteboard/adafruit_drivers/manifest.py")
#freeze("./modules", ("freezetest.py"))
#include("$(MPY_DIR)/extmod/webrepl/manifest.py")
